/**
 * Typed manifest for the Amsterdam NOW render-ready HTML templates.
 *
 * These 19 files (in this same directory) come from Claude Design — see
 * docs/design/social-templates/HANDOFF-README.md for the hotspot/event set and
 * CAROUSEL_PLACEHOLDERS.md for the rest. The eleven agenda, gids and lijstje
 * files follow the "Carousel — Templates v2" board: one full-bleed photo per
 * slide, a soft veil, a centred text band (a white rule or the item number,
 * then the headline, then an optional supporting quote), an optional red tag
 * or badge top-right, an optional place line bottom-left and the Amsterdam NOW
 * logo bottom-right. Those three families are what that board covers; hotspot
 * and event keep the older design set and are retired in lib/now-carousel.ts,
 * so they are not offered for new carousels.
 *
 * The files are used as-is: {{placeholder}} tokens get string-replaced, then
 * the file is screenshotted at its exact pixel size (lib/renderer-now.ts). Do
 * not reimplement the markup; this manifest only describes it. The eleven v2
 * files are generated by scripts/build-now-templates-v2.ts, which preserves
 * their @font-face blocks verbatim.
 *
 * Een placeholder-vlag bepaalt wie een token vult. isUrl, enumValues,
 * zeroPadTo, autoCount en fromArticleTitle worden door de applicatie ingevuld
 * (zie de opsomming bovenin lib/now-carousel.ts); al het overige schrijft het
 * model. De redacteur kan alles behalve de genummerde tokens naderhand met de
 * hand bijstellen in de carousel-editor.
 */

export type NowTemplateFamily =
  | 'hotspot'
  | 'lijstje'
  | 'event'
  | 'agenda'
  | 'gids';

export type HotspotSlideType = 'cover' | 'detail' | 'statement' | 'cta';
export type LijstjeSlideType = 'cover' | 'item' | 'cta' | 'editie-cover';
export type EventSlideType = 'hook' | 'reason' | 'practical' | 'link';
export type AgendaSlideType = 'cover' | 'wat' | 'praktisch' | 'cta';
export type GidsSlideType = 'cover' | 'item' | 'cta';

/** Union of all slide types across families. Scope with `family` for a unique key. */
export type NowSlideType =
  | HotspotSlideType
  | LijstjeSlideType
  | EventSlideType
  | AgendaSlideType
  | GidsSlideType;

export interface NowPlaceholderSpec {
  /** Token name, without the {{ }} delimiters. */
  name: string;
  /** What content belongs here, for whoever fills in `values`. */
  description: string;
  /**
   * True for tokens added after carousels were already stored. Slides written
   * before the token existed simply have no value for it, which is not an
   * error: validateNowSlides accepts the gap and lib/renderer-now.ts
   * substitutes an empty string. The templates hide an empty optional element
   * (`:empty{display:none}`) so nothing is left behind visually.
   */
  optional?: boolean;
  /**
   * True when the value is inserted inside a CSS `url(...)` (an image URL).
   * Must NOT be HTML-escaped — only CSS-string-escaped (quotes/backslashes).
   */
  isUrl?: boolean;
  /**
   * Fixed literal values this placeholder accepts (e.g. layout_richting).
   * Inserted verbatim — not HTML-escaped — because it doubles as a CSS class name.
   */
  enumValues?: readonly string[];
  /** Numeric value must be zero-padded to this many digits (e.g. item_nummer -> "01"). */
  zeroPadTo?: number;
  /**
   * Filled with the number of slides the carousel's repeated step produces
   * (the lijstje cover states how many entries follow), so the count can
   * never disagree with the actual list.
   */
  autoCount?: boolean;
  /**
   * The design contract lets the editor place a literal <br> in this token to
   * control where the line breaks (see docs/design/social-templates/
   * CAROUSEL_PLACEHOLDERS.md). The value is still HTML-escaped; only <br> is
   * restored afterwards.
   */
  allowsLineBreak?: boolean;
  /**
   * Gevuld met de titel van het artikel, woordelijk — nooit door het model
   * geschreven. Alleen de kop van de openingsslide: wie de carousel ziet
   * langskomen leest dezelfde kop als boven het artikel. De redacteur mag hem
   * in de editor alsnog inkorten (zie editablePlaceholders in
   * lib/now-carousel.ts).
   */
  fromArticleTitle?: boolean;
}

export interface NowTemplateSpec {
  family: NowTemplateFamily;
  slideType: NowSlideType;
  /** Filename inside templates/now/, e.g. "hotspot_cover.html". */
  file: string;
  dimensions: { width: number; height: number };
  placeholders: NowPlaceholderSpec[];
  /** How often this slide type may/must appear within one carousel or story. */
  reuse: {
    min: number;
    max: number;
    description: string;
  };
}

const HOTSPOT_DIMENSIONS = { width: 1080, height: 1350 };
const LIJSTJE_DIMENSIONS = { width: 1080, height: 1350 };
const EVENT_DIMENSIONS = { width: 1080, height: 1920 };
const AGENDA_DIMENSIONS = { width: 1080, height: 1350 };
const GIDS_DIMENSIONS = { width: 1080, height: 1350 };

export const NOW_TEMPLATE_MANIFEST: readonly NowTemplateSpec[] = [
  // --- Hotspot carousel (new restaurants, shops, places) ---
  {
    family: 'hotspot',
    slideType: 'cover',
    file: 'hotspot_cover.html',
    dimensions: HOTSPOT_DIMENSIONS,
    placeholders: [
      { name: 'cover_image_url', description: 'Full-bleed cover photo URL', isUrl: true },
      { name: 'categorie', description: 'Red uppercase category label, e.g. "RESTAURANT"' },
      {
        name: 'titel_hook',
        description: 'Large white headline — the article title, verbatim',
        fromArticleTitle: true,
      },
    ],
    reuse: { min: 1, max: 1, description: 'Always slide 1 of the hotspot carousel.' },
  },
  {
    family: 'hotspot',
    slideType: 'detail',
    file: 'hotspot_detail.html',
    dimensions: HOTSPOT_DIMENSIONS,
    placeholders: [
      { name: 'detail_image_url', description: 'Detail photo, 60% width', isUrl: true },
      { name: 'detail_label', description: 'Small red uppercase label above the title' },
      { name: 'detail_title', description: 'Detail slide headline' },
      { name: 'detail_body', description: '2-3 sentence body copy' },
      {
        name: 'layout_richting',
        description: 'Which side the photo sits on; flips flex-direction via CSS class.',
        enumValues: ['foto-links', 'foto-rechts'],
      },
    ],
    reuse: { min: 1, max: 3, description: 'Reused up to 3x, typically slides 3-5, alternating layout_richting.' },
  },
  {
    family: 'hotspot',
    slideType: 'statement',
    file: 'hotspot_statement.html',
    dimensions: HOTSPOT_DIMENSIONS,
    placeholders: [
      { name: 'quote', description: 'Centered editorial pull-quote' },
    ],
    reuse: { min: 1, max: 1, description: 'One statement slide per carousel.' },
  },
  {
    family: 'hotspot',
    slideType: 'cta',
    file: 'hotspot_cta.html',
    dimensions: HOTSPOT_DIMENSIONS,
    placeholders: [
      { name: 'plek_naam', description: 'Venue name' },
      { name: 'wijk', description: 'Neighborhood' },
    ],
    reuse: { min: 1, max: 1, description: 'Always the final slide.' },
  },

  // --- Lijstje carousel ("N best X in Amsterdam") ---
  {
    family: 'lijstje',
    slideType: 'cover',
    file: 'lijstje_cover.html',
    dimensions: LIJSTJE_DIMENSIONS,
    placeholders: [
      { name: 'cover_image_url', description: 'Full-bleed cover photo URL', isUrl: true },
      {
        name: 'aantal_items',
        description: 'Big number in the red badge top-right: how many items the list has',
        autoCount: true,
      },
      {
        name: 'categorie',
        description:
          'Short uppercase label under the number in the red badge, max ~14 characters — one word if you can',
      },
      {
        name: 'kop',
        description:
          'Centered headline — the article title, verbatim. Filled by the application; the editor may shorten it',
        fromArticleTitle: true,
      },
      {
        name: 'quote',
        description:
          'Optional supporting line under the headline, in Oswald Light: the tension the headline dropped. Max ~90 characters, at most 2 lines. No quote marks around it — the design adds them. Leave empty if you have nothing to add',
        optional: true,
      },
    ],
    reuse: { min: 1, max: 1, description: 'Always slide 1 of the lijstje carousel.' },
  },
  {
    family: 'lijstje',
    slideType: 'item',
    file: 'lijstje_item.html',
    dimensions: LIJSTJE_DIMENSIONS,
    placeholders: [
      {
        name: 'item_nummer',
        description: 'Rank number, white numeral above the headline',
        zeroPadTo: 2,
      },
      { name: 'item_image_url', description: 'Full-bleed item photo', isUrl: true },
      {
        name: 'item_naam',
        description: 'Place name, centered headline, at most 2 lines — the name only, no tagline',
      },
      {
        name: 'item_wijk',
        description:
          'Neighborhood only, on the bottom-left line — template prefixes it with "Amsterdam " automatically.',
      },
      {
        name: 'item_body',
        description:
          'Supporting line under the name, in Oswald Light: the one concrete thing that makes this place worth the entry. Max ~90 characters, at most 2 lines. No quote marks around it — the design adds them',
      },
    ],
    reuse: { min: 1, max: 10, description: 'Reused once per ranked entry, up to 10x.' },
  },
  {
    family: 'lijstje',
    slideType: 'cta',
    file: 'lijstje_cta.html',
    dimensions: LIJSTJE_DIMENSIONS,
    placeholders: [
      {
        name: 'cta_titel',
        description:
          'Centered CTA headline, 3 to 5 words, at most 2 lines, e.g. "DE VOLLEDIGE LIJST"; <br> allowed',
        allowsLineBreak: true,
      },
      {
        name: 'cta_sub',
        description:
          'Supporting line under the CTA headline, in Oswald Light, e.g. "Staat in onze bio". Max ~70 characters, at most 2 lines. No quote marks around it — the design adds them',
      },
    ],
    reuse: { min: 1, max: 1, description: 'Always the final slide.' },
  },

  // --- Event story (Instagram Stories, 4 frames) ---
  {
    family: 'event',
    slideType: 'hook',
    file: 'event_hook.html',
    dimensions: EVENT_DIMENSIONS,
    placeholders: [
      { name: 'event_image_url', description: 'Full-bleed event photo', isUrl: true },
      { name: 'datum', description: 'Date, white uppercase, e.g. "VRIJDAG 23 MEI"' },
      {
        name: 'event_titel',
        description: 'White headline — the article title, verbatim',
        fromArticleTitle: true,
      },
    ],
    reuse: { min: 1, max: 1, description: 'Always frame 1.' },
  },
  {
    family: 'event',
    slideType: 'reason',
    file: 'event_reason.html',
    dimensions: EVENT_DIMENSIONS,
    placeholders: [
      { name: 'event_image_url', description: 'Full-bleed photo behind the 50% dark overlay', isUrl: true },
      { name: 'reden_zin', description: 'One centered white sentence: why go' },
    ],
    reuse: { min: 1, max: 1, description: 'Always frame 2.' },
  },
  {
    family: 'event',
    slideType: 'practical',
    file: 'event_practical.html',
    dimensions: EVENT_DIMENSIONS,
    placeholders: [
      { name: 'wanneer', description: 'WANNEER value' },
      { name: 'waar', description: 'WAAR value' },
      { name: 'prijs', description: 'PRIJS value' },
    ],
    reuse: { min: 1, max: 1, description: 'Always frame 3, white background with practical info.' },
  },
  {
    family: 'event',
    slideType: 'link',
    file: 'event_link.html',
    dimensions: EVENT_DIMENSIONS,
    placeholders: [
      { name: 'event_image_url', description: 'Bottom two-thirds photo', isUrl: true },
    ],
    reuse: {
      min: 1,
      max: 1,
      description:
        'Always frame 4. Top third stays clean white for the native Instagram link sticker (added manually in-app).',
    },
  },

  // --- Agenda carousel (one event, 4 slides) ---
  {
    family: 'agenda',
    slideType: 'cover',
    file: 'agenda_cover.html',
    dimensions: AGENDA_DIMENSIONS,
    placeholders: [
      { name: 'cover_image_url', description: 'Full-bleed cover photo URL', isUrl: true },
      {
        name: 'kicker',
        description:
          'Uppercase label in the red tag top-right, one word, e.g. "AGENDA" or "CULTUUR"',
      },
      {
        name: 'datum',
        description:
          'Date, first half of the bottom-left line, e.g. "25 JUL — 16 AUG". Kept short: the location follows it after a middot',
      },
      {
        name: 'event_titel',
        description:
          'Centered headline — the article title, verbatim. Filled by the application; the editor may shorten it and may use <br>',
        allowsLineBreak: true,
        fromArticleTitle: true,
      },
      {
        name: 'locatie',
        description:
          'Venue and area, second half of the bottom-left line, e.g. "NDSM — AMSTERDAM NOORD"',
      },
      {
        name: 'quote',
        description:
          'Optional supporting line under the headline, in Oswald Light: the tension the headline dropped. Max ~90 characters, at most 2 lines. No quote marks around it — the design adds them. Leave empty if you have nothing to add',
        optional: true,
      },
    ],
    reuse: { min: 1, max: 1, description: 'Always slide 1 of the agenda carousel.' },
  },
  {
    family: 'agenda',
    slideType: 'wat',
    file: 'agenda_wat.html',
    dimensions: AGENDA_DIMENSIONS,
    placeholders: [
      { name: 'sfeer_image_url', description: 'Atmospheric photo URL', isUrl: true },
      {
        name: 'label',
        description: 'Uppercase label in the red tag top-right, e.g. "WAT IS HET?"',
      },
      {
        name: 'reden_zin',
        description:
          'Why go, as a headline and not a sentence: 3 to 5 words, max ~40 characters, at most 3 lines. Put the argument itself in the quote below',
      },
      {
        name: 'quote',
        description:
          'Optional supporting line under the headline, in Oswald Light: the reason to go, concretely. Max ~90 characters, at most 2 lines. No quote marks around it — the design adds them. Leave empty if you have nothing to add',
        optional: true,
      },
    ],
    reuse: {
      min: 1,
      max: 1,
      description: 'Always slide 2 — the one slide whose text band sits at the top.',
    },
  },
  {
    family: 'agenda',
    slideType: 'praktisch',
    file: 'agenda_praktisch.html',
    dimensions: AGENDA_DIMENSIONS,
    placeholders: [
      {
        name: 'wanneer',
        description:
          'When it is, as the centered headline: max ~40 characters, at most 3 lines, e.g. "ELKE ZONDAG IN JULI"',
      },
      {
        name: 'wanneer_extra',
        description:
          'Supporting line under the headline, in Oswald Light: opening hours or the detail that qualifies the date. Max ~90 characters, at most 2 lines. No quote marks around it — the design adds them',
      },
      {
        name: 'waar',
        description: 'Location, first line bottom-left, max ~40 characters',
      },
      {
        name: 'waar_extra',
        description: 'Smaller second line under the location (address or area), max ~50 characters',
      },
      {
        name: 'tickets',
        description:
          'Price or admission in the red tag top-right, kept short: "GRATIS", "€ 24,50", "VANAF € 12"',
      },
      {
        name: 'tickets_extra',
        description: 'Small line under the ticket tag, max ~60 characters',
      },
      {
        name: 'praktisch_image_url',
        description:
          'Optional full-bleed photo behind the practical info; without one the slide falls back to the dark ground of the other slides',
        isUrl: true,
        optional: true,
      },
    ],
    reuse: { min: 1, max: 1, description: 'Always slide 3, practical info.' },
  },
  {
    family: 'agenda',
    slideType: 'cta',
    file: 'agenda_cta.html',
    dimensions: AGENDA_DIMENSIONS,
    placeholders: [
      {
        name: 'cta_titel',
        description:
          'Centered CTA headline, 3 to 5 words, at most 2 lines, e.g. "PLAN JE BEZOEK"; <br> allowed',
        allowsLineBreak: true,
      },
      {
        name: 'cta_sub',
        description:
          'Supporting line under the CTA headline, in Oswald Light, e.g. "Meer in de agenda". Max ~70 characters, at most 2 lines. No quote marks around it — the design adds them',
      },
    ],
    reuse: { min: 1, max: 1, description: 'Always the final slide.' },
  },

  // --- Gids carousel (cover + 2-8 items + CTA) ---
  {
    family: 'gids',
    slideType: 'cover',
    file: 'gids_cover.html',
    dimensions: GIDS_DIMENSIONS,
    placeholders: [
      { name: 'cover_image_url', description: 'Full-bleed cover photo URL', isUrl: true },
      {
        name: 'kicker',
        description: 'Uppercase label in the red tag top-right, e.g. "BUURTEN / WEST"',
      },
      {
        name: 'gids_titel',
        description:
          'Centered guide title — the article title, verbatim. Filled by the application; the editor may shorten it and may use <br>',
        allowsLineBreak: true,
        fromArticleTitle: true,
      },
      {
        name: 'gids_sub',
        description:
          'Supporting line under the title, in Oswald Light: what this guide actually promises. Max ~90 characters, at most 2 lines. No quote marks around it — the design adds them',
      },
    ],
    reuse: { min: 1, max: 1, description: 'Always slide 1 of the gids carousel.' },
  },
  {
    family: 'gids',
    slideType: 'item',
    file: 'gids_item.html',
    dimensions: GIDS_DIMENSIONS,
    placeholders: [
      { name: 'item_image_url', description: 'Full-bleed item photo', isUrl: true },
      {
        name: 'item_nummer',
        description: 'White numeral above the headline, zero-padded: 01, 02, …',
        zeroPadTo: 2,
      },
      {
        name: 'item_categorie',
        description: 'Uppercase label in the red tag top-right, one or two words',
      },
      {
        name: 'item_naam',
        description:
          'Item name, centered headline, at most 2 lines — the name only, no tagline; <br> allowed',
        allowsLineBreak: true,
      },
      {
        name: 'item_body',
        description:
          'Supporting line under the name, in Oswald Light: the one concrete thing that makes this entry worth it. Max ~90 characters, at most 2 lines. No quote marks around it — the design adds them',
      },
    ],
    reuse: {
      min: 2,
      max: 8,
      description: 'Reused 2-8x. Also the item slide of the lijstje-editie carousel.',
    },
  },
  {
    family: 'gids',
    slideType: 'cta',
    file: 'gids_cta.html',
    dimensions: GIDS_DIMENSIONS,
    placeholders: [
      {
        name: 'cta_titel',
        description:
          'Centered CTA headline, 3 to 5 words, at most 2 lines, e.g. "BEWAAR DEZE GIDS"; <br> allowed',
        allowsLineBreak: true,
      },
      {
        name: 'cta_sub',
        description:
          'Supporting line under the CTA headline, in Oswald Light. Max ~70 characters, at most 2 lines. No quote marks around it — the design adds them',
      },
    ],
    reuse: { min: 1, max: 1, description: 'Always the final slide.' },
  },

  // --- Lijstje editie-cover (pairs with the gids item slide) ---
  {
    family: 'lijstje',
    slideType: 'editie-cover',
    file: 'lijstje_editie_cover.html',
    dimensions: LIJSTJE_DIMENSIONS,
    placeholders: [
      { name: 'cover_image_url', description: 'Full-bleed cover photo URL', isUrl: true },
      {
        name: 'editie_titel',
        description:
          'Centered edition title — the article title, verbatim. Filled by the application; the editor may shorten it',
        fromArticleTitle: true,
      },
      {
        name: 'editie_footer',
        description: 'Uppercase label in the red tag top-right, e.g. "EDITIE JULI"',
      },
      {
        name: 'quote',
        description:
          'Optional supporting line under the title, in Oswald Light: what this edition is really about. Max ~90 characters, at most 2 lines. No quote marks around it — the design adds them. Leave empty if you have nothing to add',
        optional: true,
      },
    ],
    reuse: {
      min: 1,
      max: 1,
      description:
        'Alternative opener for a periodic list edition; the items that follow use the gids item slide.',
    },
  },
];

export function getNowTemplateSpec(family: NowTemplateFamily, slideType: NowSlideType): NowTemplateSpec {
  const spec = NOW_TEMPLATE_MANIFEST.find((s) => s.family === family && s.slideType === slideType);
  if (!spec) {
    throw new Error(`No NOW template found for family="${family}" slideType="${slideType}"`);
  }
  return spec;
}
